In [39]:
import numpy as np

In [40]:
arr1 = np.arange(30,70)
print(arr1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [41]:
arr1 =np.arange(50,95)
print(arr1)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94]


In [42]:
arr1 =np.arange(20,80,2)
print(arr1)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]


In [43]:
arr2 =np.arange(20,80,3)
print(arr2)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77]


In [44]:
arr3 = np.random.randint(10,40,15)
print(arr3)

[11 18 39 15 29 18 20 34 26 33 37 22 23 27 20]


In [45]:
arr3 =np.random.randint(30,50,10)
print(arr3)

[41 43 43 34 41 31 30 44 42 49]


In [46]:
arr4= np.random.randint(50,90,20)
print(arr4)

[68 61 86 70 60 77 87 51 60 82 51 77 60 75 69 84 63 86 53 53]


In [47]:
arr4 = np.zeros(10)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [48]:
arr4 = np.ones(10)
print(arr4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [49]:
arr4 = np.ones(10)

print(arr4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [51]:
arr4 = np.ones(10)*5

print(arr4)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [52]:
arr4 = np.ones(10)*10

print(arr4)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [53]:
arr4 = np.ones(10)*20

print(arr4)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [54]:
arr4 = np.ones(10)*50

print(arr4)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [55]:
n1 = np.array([10,20,30,40,50])
n2 = np.array([60,70,80,90,20])
print(f"N1 = {n1}")
print(f"N2 ={n2}")
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)

N1 = [10 20 30 40 50]
N2 =[60 70 80 90 20]
[ 70  90 110 130  70]
[-50 -50 -50 -50  30]
[ 600 1400 2400 3600 1000]
[0.16666667 0.28571429 0.375      0.44444444 2.5       ]


In [58]:
def function1():
    arr1 = ([1,7,13,105])
    print(arr1)
    print(f"Size ={arr1.size}")

In [ ]:
def function3():
    arr = np.array([10,20,30,40,50,60])
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"Dtype ={arr.dtype}")
    print(f"Item Size = {arr.itemsize}")
    print(f"Size ={arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES={arr.nbytes}")

In [66]:
import numpy as np

In [106]:
def function3():
    arr = np.array([1,7,13,105])
    print(arr)
    print(f"Type = {type(arr)}")
    print(f"Dtype ={arr.dtype}")
    print(f"Item Size = {arr.itemsize}")
    print(f"Size ={arr.size}")
    print(f"NDIM = {arr.ndim}")
    print(f"NBYTES={arr.nbytes}")

In [107]:
function3()

[  1   7  13 105]
Type = <class 'numpy.ndarray'>
Dtype =int64
Item Size = 8
Size =4
NDIM = 1
NBYTES=32


In [108]:
import numpy as np

In [117]:
a = np.arange(10,22
).reshape(3,4)
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [123]:
a = np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [124]:
a = np.arange(12,38)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [125]:
def function1():
    a = np.array([10,20,30,40,50,60],dtype=np.float16)
    print(a)
    

In [126]:
function1()

[10. 20. 30. 40. 50. 60.]


In [129]:
a= np.diag([1,1,1]).reshape(3,3)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [130]:
a= np.random.random([3,3,3])
print(a)

[[[0.17582344 0.67668759 0.37321693]
  [0.98981753 0.93303764 0.46642129]
  [0.64103165 0.49708596 0.00208169]]

 [[0.10088728 0.94396917 0.66992397]
  [0.02501549 0.96932908 0.44696709]
  [0.506084   0.34630545 0.43707137]]

 [[0.67818153 0.91335921 0.3339175 ]
  [0.78667676 0.9581618  0.50896322]
  [0.14570984 0.7879469  0.88673461]]]


In [131]:
a =np.random.random([2,3,4])
print(a)

[[[0.56569916 0.14049014 0.12069629 0.63468933]
  [0.29562141 0.02181903 0.6812667  0.51231961]
  [0.37773412 0.99680091 0.80311195 0.48278973]]

 [[0.54255278 0.62944818 0.77993728 0.63018758]
  [0.80957473 0.33651745 0.0222878  0.0322805 ]
  [0.21707221 0.89233468 0.91804567 0.52041638]]]


In [133]:
def function1():
    a = np.flip([10,20,30,40,50,60])
    print(a)

In [134]:
function1()

[60 50 40 30 20 10]


In [135]:
a =np.diag([1,2,3,4,5]).reshape(5,5)
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
